#!/usr/bin/env python3
"""Prove render_tex.py loses no prose, by inverting it and diffing.

The LaTeX target is generated by a mechanical rewrite rather than by rereading
the book, so the guarantee worth having is not that the rewrite was done
carefully but that it is reversible. This inverts the generated .tex back to
the dialect's plain prose and compares it to the same prose taken from
manuscript/sections. Any dropped, duplicated, or mangled run of text shows up
as a diff.

Citation markers are compared by count and position rather than by identity:
twelve claim ids share a bib_key (see D-062), so key -> claim_id is not a
function and cannot be inverted. Every id is separately checked to resolve, in
render_tex.py itself, which errors on any that does not.

Usage: check_tex_roundtrip.py [BOOK.tex]   (renders to a temp file if omitted)
"""
import difflib
import os
import re
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))

UNESCAPE = [
    (r"\textbackslash{}", "\\"), (r"\textasciicircum{}", "^"),
    (r"\textasciitilde{}", "~"), (r"\{", "{"), (r"\}", "}"),
    (r"\$", "$"), (r"\&", "&"), (r"\#", "#"), (r"\_", "_"), (r"\%", "%"),
]
STRUCTURAL = re.compile(
    r"^(\\(chapter\*?|section|subsection|label|begin|end|setcounter|item|"
    r"boxtitle|addcontentsline|vspace)\b|%)")


def tex_prose(path):
    """The prose of a generated .tex, as a list of normalized lines."""
    text = open(path, encoding="utf-8").read()
    body = text.split(r"\mainmatter", 1)[1].split(r"\backmatter", 1)[0]
    out = []
    for line in body.splitlines():
        s = line.strip()
        if not s or STRUCTURAL.match(s):
            # \item and \boxtitle carry prose after the command; keep it.
            m = re.match(r"^\\(item|boxtitle)\{?(.*?)\}?$", s)
            if not m:
                continue
            s = m.group(2)
        s = re.sub(r"^\\runin\{(.*)\}$", r"\1", s)
        # verse and the attribution block put several source lines on one
        # output line, separated by \\; split them back apart.
        for piece in s.split(r"\\"):
            piece = re.sub(r"\\autocite\{[^}]*\}", "<CITE>", piece)
            piece = re.sub(r"\\emph\{([^}]*)\}", r"*\1*", piece)
            for a, b in UNESCAPE:
                piece = piece.replace(a, b)
            piece = " ".join(piece.split())
            if piece:
                out.append(piece)
    return out


def source_prose():
    """The same prose taken from the dialect sections."""
    _, order = common.read_tsv(os.path.join(common.SECTIONS, "ORDER.tsv"))
    order.sort(key=lambda r: common.numkey(r["num"]))
    out = []
    for r in order:
        path = os.path.join(common.REPO, r["path"])
        lines = open(path, encoding="utf-8").read().splitlines()
        for line in lines[1:]:          # line 0 is the heading
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            if re.fullmatch(r"<</?(quote|list|box)>>", s):
                continue
            m = re.match(r"^<<h>>(.*)<</h>>$", s)
            if m:
                s = m.group(1).strip()
            m = re.match(r"^\s*(\(\d+\)|\d+[.)]|[-•*]|[a-z][.)])\s+(.*)$", s)
            if m and re.fullmatch(r"[-•]|\(?\d+[.)]|[a-z][.)]", m.group(1)):
                s = m.group(2)
            s = re.sub(r"\[\[cite:[^\]]+\]\]", "<CITE>", s)
            s = " ".join(s.split())
            if s:
                out.append(s)
    return out


def main():
    tex = sys.argv[1] if len(sys.argv) > 1 else None
    tmp = None
    if not tex:
        tmp = tempfile.NamedTemporaryFile(suffix=".tex", delete=False)
        tmp.close()
        subprocess.check_call(
            [sys.executable, os.path.join(HERE, "render_tex.py"), "-o", tmp.name],
            stdout=subprocess.DEVNULL)
        tex = tmp.name

    a, b = source_prose(), tex_prose(tex)
    if a == b:
        print("OK: %d prose lines round-trip exactly (dialect -> LaTeX -> dialect)"
              % len(a))
        rc = 0
    else:
        diff = list(difflib.unified_diff(a, b, "sections", "generated .tex", n=1))
        print("FAIL: prose differs (%d source lines, %d generated)" % (len(a), len(b)))
        sys.stdout.write("\n".join(diff[:80]) + "\n")
        if len(diff) > 80:
            print("... %d more diff lines" % (len(diff) - 80))
        rc = 1
    if tmp:
        os.unlink(tmp.name)
    return rc


if __name__ == "__main__":
    sys.exit(main())
