\subsection{The Role of Play in Moral Learning and Socialization}
\label{sec:5.7.1}
Children build much of their moral sense through play, and instruction supplies far less of it than adults assume. A child who tests a rule against a playmate — pushing it, breaking it, watching the other child's face — gets an answer no lecture supplies, delivered immediately by someone with no stake in teaching a lesson. Developmental psychologists point to play rather than direct teaching as the route by which perspective-taking, cooperation, and respect for rules actually get built \autocite{gray2013free}.

Section~\ref{sec:4.3.1}'s agents developed tool use and counter-strategies nobody had programmed through repeated competitive play, which is competence emerging from play. What this section asks is different in kind: whether play can teach a system standards for how to treat the agents it plays with.

An AI system has no biological drives, and its witnessing of its “own” winning or losing is not necessarily a felt personal experience. But a training context can still be built to have the structural features that make human-like play work as a moral teacher: actions that carry real consequences for other agents, feedback from the environment itself with no supervisor's label attached after the fact, and enough latitude that the system's choices are its “own” and not a script. These conditions may teach coordination and norm-sensitive behavior whether or not affect is present. They do not by themselves establish moral formation: without some process through which another agent's welfare comes to matter, play may produce a policy that looks prosocial without producing concern for anyone.

Two existing games illustrate what a moral version of that structure looks like. Quandary walks a player through a sequence of dilemmas with no dictated right answer and scores how the player reasons rather than which option they pick \autocite{lgn2012quandary}, which is the design principle a moral-training environment would need: evaluate the deliberation itself. Hanabi, a cooperative card game where each player sees everyone's hand but their own and must communicate through the game's own restricted signals, is a standard research benchmark for the capacities morality runs on directly — modeling what a partner does and does not know, and communicating honestly inside a rule-bound system \autocite{bard2020hanabi}. Hide and Seek's payoff was adversarial and Hanabi's is cooperative, and that difference is close to the whole of what separates this section's territory from section~\ref{sec:4.3.1}'s.

\runin{What the developmental literature actually supplies}
Two of the four accounts usually cited here transfer. Piaget's constructivism — a child builds understanding by acting on the world rather than receiving it finished \autocite{piaget1962play} — transfers because the machine version is checkable: a system that refines its model of what is at stake by acting repeatedly is doing something different from a system sorting cases against a fixed label. Theory of mind transfers for the same reason, and Hanabi is why, since modeling what a partner knows is exactly what the game scores. Bandura's social learning is already section~\ref{sec:5.1.2}'s. Care ethics belongs in this chapter for a reason that is not about play at all: Carol Gilligan built the account as a critique of the stage model section~\ref{sec:5.1.1} leans on, having found that its scoring treated relational reasoning as a lower stage \autocite{gilligan1982different}.

What none of them supplies is the thing chapter~\ref{sec:3} wants. They describe how a moral sense forms in a creature under pressures a system does not face, and they do not say which of those pressures were load-bearing. A system that plays a million episodes overnight has the repetition and none of the stakes, and whether the mechanism survives that substitution is the open question rather than a detail.

\runin{Building the curriculum, and deliberating inside it}
Building play into a curriculum means being specific about the environment, the feedback, and the pace. The environment has to carry real stakes for the other agents in it, so that a system controlling a simulated vehicle in a modeled city experiences the downstream consequences of a choice instead of naming one. The difficulty has to be structured, starting with low-stakes dilemmas and escalating only once the easy cases are handled reliably. And the feedback has to attach to a specific attempt, closer to how a coach corrects a player mid-game than to how a policy is handed down in advance.

The target inside that curriculum is deliberation that stays open-ended, which simulating a single dilemma and stopping does not reach. Give a system a moral dilemma and have it build a story around it, working through several characters with genuinely conflicting interests without picking a winner; or have it argue from inside a stakeholder's position and see how its choices affect the other parties before the scenario ends. Both put the system in the position of constructing an outcome, where the alternative selects from a menu of pre-written responses. A system that only ever sees dilemmas with a single correct output learns to match patterns against that output rather than to deliberate.

None of this makes an AI system's play equivalent to a child's. A child's play is charged by stakes that matter to the child — status among peers, the sting of exclusion — where an AI system's “play” is whatever its designer wired the reward function to care about. What section~\ref{sec:5.5.1} already covers for multi-agent training a play-based framing cannot assume: whether the resulting behavior is moral learning or a policy that merely looks prosocial inside the reward function that produced it.
