#!/usr/bin/env python3
"""Generate manuscript/sections.tex -- the \\input list -- from ORDER.tsv.

Run after adding, removing, or renumbering a section. With --check, verifies
the file on disk is what generation would produce and exits non-zero if not;
that is the invariant check_all.sh runs.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common  # noqa: E402

OUT = os.path.join(common.REPO, "manuscript", "sections.tex")

HEAD = """% sections.tex -- GENERATED by finishing/tools/gen_book.py from
% sections/ORDER.tsv. Do not edit by hand; edits here are overwritten.
"""


def expected():
    out = [HEAD]
    for r in common.order_rows():
        rel = os.path.relpath(os.path.join(common.REPO, r["path"]),
                              os.path.join(common.REPO, "manuscript"))
        out.append("\\input{%s}\n" % rel[:-4])   # \input adds .tex itself
    return "".join(out)


def main():
    want = expected()
    if "--check" in sys.argv:
        got = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
        if got == want:
            print("sections.tex OK: matches ORDER.tsv (%d inputs)"
                  % want.count("\\input{"))
            return 0
        print("sections.tex STALE: not what gen_book.py would generate; re-run it")
        return 1
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(want)
    print("wrote %s (%d inputs)" % (os.path.relpath(OUT, common.REPO),
                                    want.count("\\input{")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
