#!/usr/bin/env python3
"""Three-way reconcile: manuscript headings, finishing/outline.tsv, table-of-contents.txt.

Writes finishing/reports/headings_reconcile.md. With --write-toc, regenerates
manuscript/table-of-contents.txt from the manuscript's own headings (gated on a
decision; see finishing/DECISIONS.md D-011). With --check, verifies that the TOC
on disk is what regeneration would produce and exits non-zero if it is not,
writing nothing; this is the invariant check_all.sh runs.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common  # noqa: E402

OUT = os.path.join(common.REPORTS, "headings_reconcile.md")


def toc_entries():
    out = []
    with open(common.TOC_TXT, encoding="utf-8") as f:
        for i, line in enumerate(f, 1):
            h = common.parse_heading(line)
            if h:
                out.append((i, h[0], h[1]))
    return out


def toc_expected(ms):
    """Exactly what --write-toc would write, as a single string."""
    return "".join(raw.strip() + "\n" for _, _, _, raw in ms)


def main():
    # Since D-065 the section .tex files are the source; there is no joined
    # reference text to read headings out of any more.
    heads = common.section_headings()
    src = "manuscript/sections/**.tex"
    ms = [(i, n, ttl, common.heading_line(n, ttl))
          for i, (n, ttl, _) in enumerate(heads, 1)]
    ms_map = {n: ttl for n, ttl, _ in heads}

    # The TOC is generated output (D-011). --check enforces that; --write-toc
    # produces it. Both run before the report below, so the report describes the
    # state this invocation leaves behind rather than the one it found.
    expected = toc_expected(ms)
    rel = os.path.relpath(common.TOC_TXT, common.REPO)
    if "--check" in sys.argv:
        try:
            with open(common.TOC_TXT, encoding="utf-8") as f:
                actual = f.read()
        except FileNotFoundError:
            actual = None
        if actual == expected:
            print("TOC OK: %s matches the manuscript's headings (%d entries)" % (rel, len(ms)))
            return 0
        print("TOC STALE: %s is not what the manuscript's headings would generate" % rel)
        if actual is None:
            print("  the file does not exist")
        else:
            exp_l, act_l = expected.splitlines(), actual.splitlines()
            print("  expected %d entries, found %d" % (len(exp_l), len(act_l)))
            for i in range(max(len(exp_l), len(act_l))):
                e = exp_l[i] if i < len(exp_l) else "<missing>"
                a = act_l[i] if i < len(act_l) else "<missing>"
                if e != a:
                    print("  first difference at line %d:" % (i + 1))
                    print("    manuscript: %s" % e)
                    print("    TOC:        %s" % a)
                    break
        print("  fix: python3 finishing/tools/headings.py --write-toc")
        return 1

    regenerated = False
    if "--write-toc" in sys.argv:
        with open(common.TOC_TXT, "w", encoding="utf-8") as f:
            f.write(expected)
        regenerated = True

    _, outline_rows = common.read_tsv(common.OUTLINE_TSV)
    ol_map = {r["num"]: r["title"] for r in outline_rows}
    toc = toc_entries()
    toc_map = {n: t for _, n, t in toc}

    lines = ["# Heading reconciliation", "",
             "Generated by `finishing/tools/headings.py`. Sources:",
             "",
             "- manuscript: `%s` (%d headings)" % (src, len(ms)),
             "- outline: `finishing/outline.tsv` (%d entries, from the v3b .ods column A)" % len(ol_map),
             "- TOC: `manuscript/table-of-contents.txt` (%d entries)%s" % (
                 len(toc_map), " — regenerated by this run" if regenerated else ""),
             ""]

    dups = sorted({n for n in ms_map if [x[1] for x in ms].count(n) > 1})
    lines += ["## Duplicate numbers in the manuscript", "",
              ("none" if not dups else ", ".join(dups)), ""]

    lines += ["## Manuscript vs outline (the authoritative pair)", ""]
    only_ms = sorted(set(ms_map) - set(ol_map), key=common.numkey)
    only_ol = sorted(set(ol_map) - set(ms_map), key=common.numkey)
    diff_title = [(n, ms_map[n], ol_map[n]) for n in sorted(set(ms_map) & set(ol_map), key=common.numkey)
                  if ms_map[n] != ol_map[n]]
    lines += ["- only in manuscript: %s" % (", ".join(only_ms) or "none"),
              "- only in outline: %s" % (", ".join(only_ol) or "none"),
              "- same number, different title: %d" % len(diff_title), ""]
    for n, a, b in diff_title:
        lines += ["  - `%s`" % n, "    - manuscript: %s" % a, "    - outline: %s" % b]
    lines.append("")

    lines += ["## Manuscript vs TOC (generated under D-011; enforced by --check)", ""]
    only_ms_t = sorted(set(ms_map) - set(toc_map), key=common.numkey)
    only_toc = sorted(set(toc_map) - set(ms_map), key=common.numkey)
    diff_t = [(n, ms_map[n], toc_map[n]) for n in sorted(set(ms_map) & set(toc_map), key=common.numkey)
              if ms_map[n] != toc_map[n]]
    lines += ["- only in manuscript (%d): %s" % (len(only_ms_t), ", ".join(only_ms_t) or "none"),
              "- only in TOC (%d): %s" % (len(only_toc), ", ".join(only_toc) or "none"),
              "- same number, different title (%d):" % len(diff_t), ""]
    for n, a, b in diff_t:
        lines += ["  - `%s`" % n, "    - manuscript: %s" % a, "    - TOC: %s" % b]
    lines.append("")

    empty = []
    for num, _, path in heads:
        with open(os.path.join(common.REPO, path), encoding="utf-8") as f:
            body = f.read().splitlines()
        # drop the heading command, its optional \addcontentsline, and \label
        rest = [l for l in body[1:] if l.strip()
                and not l.startswith(("\\label{", "\\addcontentsline{"))]
        if not rest:
            empty.append(num)
    lines += ["## Headings with no body text", "",
              ", ".join(empty) or "none", ""]

    os.makedirs(common.REPORTS, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s" % OUT)
    print("manuscript=%d outline=%d toc=%d; ms-vs-outline title diffs=%d; empty=%d"
          % (len(ms), len(ol_map), len(toc_map), len(diff_title), len(empty)))

    if regenerated:
        print("regenerated %s" % common.TOC_TXT)
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
