#!/usr/bin/env python3
"""Three-way reconcile: manuscript headings, finishing/outline.tsv, table-of-contents.txt.

Writes finishing/reports/headings_reconcile.md. With --write-toc, regenerates
manuscript/table-of-contents.txt from the manuscript's own headings (gated on a
decision; see finishing/DECISIONS.md D-011).
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common  # noqa: E402

OUT = os.path.join(common.REPORTS, "headings_reconcile.md")


def toc_entries():
    out = []
    with open(common.TOC_TXT, encoding="utf-8") as f:
        for i, line in enumerate(f, 1):
            h = common.parse_heading(line)
            if h:
                out.append((i, h[0], h[1]))
    return out


def main():
    # The build output, not the frozen 2024 file: after P1 those differ, and the
    # TOC must describe the book as it now is.
    build = os.path.join(common.REPO, "manuscript", "parseable_text_v4.txt")
    src = build if os.path.exists(build) else common.V3B
    ms = common.headings_in(src)
    ms_map = {n: t for _, n, t, _ in ms}
    _, outline_rows = common.read_tsv(common.OUTLINE_TSV)
    ol_map = {r["num"]: r["title"] for r in outline_rows}
    toc = toc_entries()
    toc_map = {n: t for _, n, t in toc}

    lines = ["# Heading reconciliation", "",
             "Generated by `finishing/tools/headings.py`. Sources:",
             "",
             "- manuscript: `%s` (%d headings)" % (os.path.relpath(src, common.REPO), len(ms)),
             "- outline: `finishing/outline.tsv` (%d entries, from the v3b .ods column A)" % len(ol_map),
             "- stale TOC: `manuscript/table-of-contents.txt` (%d entries)" % len(toc_map),
             ""]

    dups = sorted({n for n in ms_map if [x[1] for x in ms].count(n) > 1})
    lines += ["## Duplicate numbers in the manuscript", "",
              ("none" if not dups else ", ".join(dups)), ""]

    lines += ["## Manuscript vs outline (the authoritative pair)", ""]
    only_ms = sorted(set(ms_map) - set(ol_map), key=common.numkey)
    only_ol = sorted(set(ol_map) - set(ms_map), key=common.numkey)
    diff_title = [(n, ms_map[n], ol_map[n]) for n in sorted(set(ms_map) & set(ol_map), key=common.numkey)
                  if ms_map[n] != ol_map[n]]
    lines += ["- only in manuscript: %s" % (", ".join(only_ms) or "none"),
              "- only in outline: %s" % (", ".join(only_ol) or "none"),
              "- same number, different title: %d" % len(diff_title), ""]
    for n, a, b in diff_title:
        lines += ["  - `%s`" % n, "    - manuscript: %s" % a, "    - outline: %s" % b]
    lines.append("")

    lines += ["## Manuscript vs stale TOC (historical; retired under D-011)", ""]
    only_ms_t = sorted(set(ms_map) - set(toc_map), key=common.numkey)
    only_toc = sorted(set(toc_map) - set(ms_map), key=common.numkey)
    diff_t = [(n, ms_map[n], toc_map[n]) for n in sorted(set(ms_map) & set(toc_map), key=common.numkey)
              if ms_map[n] != toc_map[n]]
    lines += ["- only in manuscript (%d): %s" % (len(only_ms_t), ", ".join(only_ms_t) or "none"),
              "- only in TOC (%d): %s" % (len(only_toc), ", ".join(only_toc) or "none"),
              "- same number, different title (%d):" % len(diff_t), ""]
    for n, a, b in diff_t:
        lines += ["  - `%s`" % n, "    - manuscript: %s" % a, "    - TOC: %s" % b]
    lines.append("")

    empty = []
    with open(src, encoding="utf-8") as f:
        text = f.readlines()
    idx = {ln: (n, t) for ln, n, t, _ in ms}
    starts = sorted(idx)
    for i, ln in enumerate(starts):
        end = starts[i + 1] - 1 if i + 1 < len(starts) else len(text)  # 0-based end
        body = "".join(text[ln:end]).strip()
        if not body:
            empty.append(idx[ln][0])
    lines += ["## Headings with no body text before the next heading", "",
              ", ".join(empty) or "none", ""]

    os.makedirs(common.REPORTS, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s" % OUT)
    print("manuscript=%d outline=%d toc=%d; ms-vs-outline title diffs=%d; empty=%d"
          % (len(ms), len(ol_map), len(toc_map), len(diff_title), len(empty)))

    if "--write-toc" in sys.argv:
        with open(common.TOC_TXT, "w", encoding="utf-8") as f:
            for _, n, t, raw in ms:
                f.write(raw.strip() + "\n")
        print("regenerated %s" % common.TOC_TXT)


if __name__ == "__main__":
    main()
