#!/usr/bin/env python3
r"""Round-trip the manuscript through Overleaf: build a package, take the zip back.

`export` writes a zip Overleaf compiles as it stands. `import` applies an
Overleaf zip to the working tree and then repairs what the edit invalidated. The
two halves share a manifest carried inside the zip, and that manifest is what
makes the round trip safe rather than merely possible.

WHAT THE ROUND TRIP IS UP AGAINST. Three facts about this repository make an
unzip over the tree wrong:

  1. TWO FILES ARE GENERATED. `manuscript/sections.tex` comes from
     `sections/ORDER.tsv` by gen_book.py, and `manuscript/table-of-contents.txt`
     from the headings by headings.py. sections.tex has to be in the package or
     Overleaf cannot compile, so it goes out and is then IGNORED on the way back
     and regenerated instead. The TOC is not in the package at all.
  2. FOUR FILES CARRY EACH HEADING. The .tex heading is authoritative (D-011);
     ORDER.tsv, outline.tsv and ledger.tsv each keep a copy of the title. A
     retitle in Overleaf makes check_structure.py fail on ORDER.tsv, fatally.
     Import syncs all three copies and prints every line it changed.
  3. THE REPOSITORY MOVES WHILE THE AUTHOR EDITS. A pass can revise a section
     between the export and the import, and writing the Overleaf copy over it
     would revert that work with nothing on the page to say so. The manifest
     records both what was exported and what the repository held at the time, so
     import can tell "Overleaf changed this" from "the repository changed this"
     and refuses the case where both did.

THE ONE PATH REWRITE. preamble.tex reads `../finishing/refs.bib`, which escapes
the package root, and an Overleaf project has no path outside itself. Export
rewrites that one line to `refs.bib`; import reverses it. The reversal is an
exact match and is counted: if the line is not there to reverse, the file is
reported and not applied, rather than guessed at. Nothing else is rewritten --
book.tex and every section file travel byte for byte.

WHAT THIS DOES NOT DO, AND WILL NOT. It does not add, delete, renumber or move a
section. Those are structural and cost more than a file write: a new section
needs rows in ORDER.tsv, outline.tsv and ledger.tsv, and a renumber needs a
renumber-map plus a sweep of every `\ref` pointing at it. All four are DETECTED
and REPORTED, and the import writes nothing at all when it finds one, rather
than half-doing it.

It also cannot see anything the invariants do not cover. What comes back is
prose, and prose is read, not checked. `check_all.sh` runs at the end and its
result is printed; a green suite means the structure survived the trip, not that
the writing is good.

Packages live OUTSIDE the repository, in `~/book-scratch/overleaf/` by default,
next to where choose-a-random-page.py writes. A zip of the manuscript inside the
tree is a build product that would be committed, so both directions refuse a
path under the repository root rather than warning about it.

  export                          write the package    (~/book-scratch/overleaf/)
  import ZIP --dry-run            report, write nothing     ALWAYS DO THIS FIRST
  import ZIP                      apply, repair, check
"""
import argparse
import datetime
import hashlib
import json
import os
import subprocess
import sys
import zipfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common  # noqa: E402

TOOLS = os.path.dirname(os.path.abspath(__file__))
MANIFEST = "overleaf-manifest.json"
READMEF = "OVERLEAF-README.md"

# Generated by gen_book.py. Shipped so Overleaf can compile, never read back.
GENERATED = {"sections.tex"}
# The package's own scaffolding: ours, not the book's, and never applied.
SCAFFOLD = {MANIFEST, READMEF}

# (zip path, repo path) for everything that is not a section file.
FIXED = [
    ("book.tex", "manuscript/book.tex"),
    ("preamble.tex", "manuscript/preamble.tex"),
    ("sections.tex", "manuscript/sections.tex"),
    ("refs.bib", "finishing/refs.bib"),
]

# (zip path, text in the repo, text in the package). Applied on export, reversed
# on import, exact-match and counted in both directions.
REWRITES = [
    ("preamble.tex",
     "\\addbibresource{../finishing/refs.bib}",
     "\\addbibresource{refs.bib}"),
]

# LaTeX build products and OS litter. An Overleaf source download carries none
# of these, but a project that had files uploaded into it can, and a zip
# repacked by a file manager brings the second kind. Dropped without comment;
# anything else unrecognized is reported instead.
IGNORE_SUFFIX = (".aux", ".log", ".bbl", ".bcf", ".blg", ".fls", ".fdb_latexmk",
                 ".out", ".toc", ".synctex.gz", ".run.xml", ".pdf", ".dvi",
                 ".xdv", ".lof", ".lot", ".nav", ".snm", ".vrb")
IGNORE_NAME = (".DS_Store", "Thumbs.db", "output.pdf", "latexmkrc", ".latexmkrc")

# Packages live outside the repository. A zip of the manuscript inside the tree
# is a build product that would land in a commit, and the round trip writes one
# every time it runs; `~/book-scratch/` is where choose-a-random-page.py already
# puts its output, so this joins it rather than inventing a second place.
SCRATCH = os.path.join(os.path.expanduser("~"), "book-scratch", "overleaf")

MAX_MEMBER_BYTES = 8 * 1024 * 1024      # no file in the book is near this
MAX_TOTAL_BYTES = 64 * 1024 * 1024

# num level -> the heading command that sets it. Verified against all 137
# sections, and true until D-406 separated identity from position. Kept as
# the record of what a number used to imply; read nothing from it (D-415).
LEVEL_CMD = {1: "chapter", 2: "section", 3: "subsection"}


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def sha256(b):
    return hashlib.sha256(b).hexdigest()


def read_bytes(path):
    with open(path, "rb") as f:
        return f.read()


def git(*args, **kw):
    r = subprocess.run(("git",) + args, cwd=common.REPO,
                       capture_output=True, text=True)
    if kw.get("check", True) and r.returncode:
        sys.exit("git %s failed: %s" % (" ".join(args), r.stderr.strip()))
    return r.stdout.strip()


def run_tool(*argv):
    """Run one of the repository's own tools from the repo root, echoing it."""
    print("  $ %s" % " ".join(argv))
    cmd = list(argv)
    if cmd[0].endswith(".py"):
        cmd.insert(0, sys.executable)
    r = subprocess.run(cmd, cwd=common.REPO, capture_output=True, text=True)
    for line in (r.stdout + r.stderr).splitlines():
        print("    %s" % line)
    return r.returncode


def outside_repo(path, what):
    """Refuse a package path inside the repository, and say why.

    Both directions are checked. An exported zip inside the tree is a build
    product that would be committed; an imported one is the same file arriving,
    and `git status` would show it as untracked in the middle of a diff the
    author is trying to read.
    """
    real = os.path.realpath(path)
    repo = os.path.realpath(common.REPO)
    if real == repo or real.startswith(repo + os.sep):
        sys.exit("refusing: %s is inside the repository (%s).\n"
                 "  Packages belong outside it -- %s is the default.\n"
                 "  A zip of the manuscript in the tree is a build product, and\n"
                 "  it would land in the next commit."
                 % (what, os.path.relpath(real, repo), SCRATCH))


def zip_path_for(repo_path):
    """The package path a repository path travels as."""
    if repo_path == "finishing/refs.bib":
        return "refs.bib"
    if repo_path.startswith("manuscript/"):
        return repo_path[len("manuscript/"):]
    raise ValueError("no package path for %s" % repo_path)


def package_files():
    """[(zip path, repo path)] -- everything the package carries."""
    out = list(FIXED)
    _, rows = common.read_tsv(os.path.join(common.SECTIONS, "ORDER.tsv"))
    rows.sort(key=lambda r: common.numkey(r["num"]))
    for r in rows:
        out.append((zip_path_for(r["path"]), r["path"]))
    return out


def rewrite(zip_rel, text, forward):
    """Apply (forward) or reverse a package rewrite. Returns (text, error)."""
    for zp, repo_text, zip_text in REWRITES:
        if zp != zip_rel:
            continue
        src, dst = (repo_text, zip_text) if forward else (zip_text, repo_text)
        n = text.count(src)
        if n != 1:
            return None, ("expected exactly one %r, found %d -- the line the "
                          "package rewrites was edited or removed" % (src, n))
        text = text.replace(src, dst)
    return text, None


def normalize(raw, reference):
    """Decode a returned file, and report what had to be repaired to read it.

    Overleaf itself writes UTF-8 with LF endings. A file that has been through a
    Windows editor or a spreadsheet on the way can pick up CRLF or a BOM, and
    both would land in the manuscript as a real diff on every line.

    The final newline is restored only when the REFERENCE -- the repository's
    own copy -- has one. Imposing it as a convention instead manufactured an
    edit on the first test run: one file in the manuscript,
    sections/ch12/12_02_03.tex, ends without a newline, and normalizing it
    reported an Overleaf edit to a file nobody had opened.
    """
    notes = []
    if raw.startswith(b"\xef\xbb\xbf"):
        raw = raw[3:]
        notes.append("stripped a UTF-8 BOM")
    if b"\r\n" in raw:
        raw = raw.replace(b"\r\n", b"\n")
        notes.append("converted CRLF line endings to LF")
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as e:
        return None, ["not valid UTF-8 (%s)" % e]
    if text and not text.endswith("\n") and reference.endswith(b"\n"):
        text += "\n"
        notes.append("restored the final newline the repository's copy has")
    return text, notes


def set_tsv_cell(path, key_idx, key, val_idx, value):
    """Rewrite one cell of a TSV in place, by line, touching nothing else.

    Deliberately not common.write_tsv: that pads every row to the header width
    and would rewrite all 137 rows of a file to change one, burying the edit.
    """
    with open(path, encoding="utf-8", newline="") as f:
        lines = f.readlines()
    changed = False
    for i, line in enumerate(lines):
        if i == 0:
            continue
        nl = "\n" if line.endswith("\n") else ""
        parts = line.rstrip("\n").split("\t")
        if len(parts) <= max(key_idx, val_idx) or parts[key_idx] != key:
            continue
        if parts[val_idx] == value:
            return False
        parts[val_idx] = value
        lines[i] = "\t".join(parts) + nl
        changed = True
        break
    if changed:
        with open(path, "w", encoding="utf-8", newline="") as f:
            f.writelines(lines)
    return changed


def heading_of(text):
    """(command, starred, num, title) from a section file's text, else None."""
    lines = text.splitlines(True)
    if not lines:
        return None
    first = lines[0].rstrip("\n")
    m = common.TEX_HEAD_RE.match(first)
    if not m:
        return None
    starred = "*" in first.split("{", 1)[0]
    for line in lines[1:4]:
        lab = common.TEX_LABEL_RE.match(line.rstrip("\n"))
        if lab:
            return m.group(1), starred, lab.group(1), m.group(2).strip()
    return None


# --------------------------------------------------------------------------
# export
# --------------------------------------------------------------------------

README_TEMPLATE = """# Antifascist Intelligence -- Overleaf package

Built by `finishing/tools/overleaf.py export` on {date} from commit `{commit}`{dirty}.
{count} files: the master, the preamble, the generated input list, {nsec} section
files, and the bibliography.

## Before the first compile

**Set the compiler to LuaLaTeX.** Gear icon -> Compiler -> LuaLaTeX. The book
loads `fontspec` and will not build under pdfLaTeX. Overleaf's documentation
gives that menu as the way to set the compiler, so the package does not try to
set it from inside a file.

**The main document is `book.tex`.** Overleaf picks it by scanning for
`\\documentclass`, and `book.tex` is the only file in the package carrying one,
so a fresh upload should select it unaided. If it does not -- a project
remembers the main file it was given, so re-uploading into one that already
chose wrong keeps the wrong choice -- set it from the file tree: right-click
`book.tex` -> Set as Main File, or Menu -> Main document.

The symptom of the wrong main file is a build ending `<*> preamble.tex` and
`(job aborted, no legal \\end found)`. That is TeX handed a file with no
`\\begin{{document}}`, reading to the end looking for the matching `\\end`. It
means the entry point is wrong, not the package (D-170).

The bibliography is biblatex with the biber backend, which Overleaf runs on its
own. The body font is TeX Gyre Pagella, which ships with TeX Live; if the first
build cannot find it, that line is the second one in `preamble.tex`.

## What to edit

- `sections/chNN/*.tex` -- the prose, one file per section. This is the point.
- `preamble.tex` -- the typesetting.
- `book.tex` -- the master.
- `refs.bib` -- the bibliography.

## What not to do here

- **Do not edit `sections.tex`.** It is generated from `sections/ORDER.tsv` in
  the repository, and the import regenerates it. Edits are discarded.
- **Do not add, delete, rename or renumber section files.** Each section has
  rows in three tracking files and a `\\label` other sections point at, none of
  which are in this package. The import detects all four and stops without
  writing anything, so nothing is lost -- but the work has to be done in the
  repository instead.
- **Do not change a `\\label{{sec:N}}` line.** That is the section's number.
- **Do not move `\\documentclass` into `preamble.tex`.** It is in `book.tex` so
  that Overleaf's main-file detection lands on the master (D-170).
- **Retitling is fine.** Change the text inside `\\section{{...}}` and the import
  syncs the three copies the repository keeps of the title.
- **Do not delete `{manifest}`.** The import reads it to tell your edits from
  any the repository made while you were editing. Without it the import refuses
  to run unless it is forced past this.
- Straight quotes and `--` dashes fail the repository's typography check. Write
  the characters themselves: " " and -- (em) and - (en).

## Getting it back

Menu -> Download -> Source. Then, in the repository:

    python3 finishing/tools/overleaf.py import ~/Downloads/PROJECT.zip --dry-run
    python3 finishing/tools/overleaf.py import ~/Downloads/PROJECT.zip
    git diff
"""


def cmd_export(args):
    files = package_files()
    nsec = len(files) - len(FIXED)

    if not args.no_check:
        print("== invariants before export")
        rc = run_tool("bash", "finishing/tools/check_all.sh")
        if rc:
            print("  WARNING: check_all.sh fails on the tree being exported. The")
            print("  package is still written -- export reads and does not write --")
            print("  but whatever is broken travels with it.")

    commit = git("rev-parse", "HEAD")
    dirty = bool(git("status", "--porcelain"))
    date = datetime.datetime.now().strftime("%Y-%m-%d")

    if args.out is None:
        out = os.path.join(SCRATCH, "antifascist-intelligence_%s.zip" % date)
    else:
        out = os.path.abspath(os.path.expanduser(args.out))
    outside_repo(out, "the package")
    os.makedirs(os.path.dirname(out), exist_ok=True)

    manifest = {
        "format": 1,
        "tool": "finishing/tools/overleaf.py",
        "exported": datetime.datetime.now(datetime.timezone.utc)
                    .strftime("%Y-%m-%dT%H:%M:%SZ"),
        "commit": commit,
        "commit_dirty": dirty,
        "generated": sorted(GENERATED),
        "rewrites": [{"zip": z, "repo_text": r, "zip_text": p}
                     for z, r, p in REWRITES],
        "files": {},
    }

    staged = []
    for zip_rel, repo_rel in files:
        raw = read_bytes(os.path.join(common.REPO, repo_rel))
        repo_digest = sha256(raw)
        text, err = rewrite(zip_rel, raw.decode("utf-8"), forward=True)
        if err:
            sys.exit("export: %s: %s" % (repo_rel, err))
        blob = text.encode("utf-8")
        staged.append((zip_rel, blob))
        manifest["files"][zip_rel] = {
            "repo": repo_rel,
            "repo_sha256": repo_digest,     # the repository's bytes
            "zip_sha256": sha256(blob),     # what Overleaf was handed
        }

    readme = README_TEMPLATE.format(
        date=date, commit=commit[:12],
        dirty=" (with uncommitted changes in the tree)" if dirty else "",
        count=len(files), nsec=nsec, manifest=MANIFEST)

    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for zip_rel, blob in staged:
            zf.writestr(zip_rel, blob)
        zf.writestr(READMEF, readme.encode("utf-8"))
        zf.writestr(MANIFEST, (json.dumps(manifest, indent=2,
                                          sort_keys=True) + "\n").encode("utf-8"))

    size = os.path.getsize(out)
    print()
    print("wrote %s (%.1f MB)" % (out, size / 1e6))
    print("  %d files: %d section files, %s, plus %s and %s"
          % (len(files) + 2, nsec, ", ".join(z for z, _ in FIXED),
             READMEF, MANIFEST))
    print("  from commit %s%s" % (commit[:12],
                                  ", tree dirty" if dirty else ""))
    if dirty:
        print("  NOTE: uncommitted changes are in the package. The manifest")
        print("  records the working-tree bytes, so the round trip is still")
        print("  exact -- but the commit named above does not describe it.")
    print()
    print("Upload to Overleaf: New Project -> Upload Project -> this zip.")
    print("Then set the compiler to LuaLaTeX (gear icon -> Compiler); it does")
    print("not build under pdfLaTeX. The main document is book.tex, the only")
    print("file carrying \\documentclass, so Overleaf should select it unaided;")
    print("a build ending 'no legal \\end found' means it did not (D-170).")
    print("%s in the project repeats both." % READMEF)
    return 0


# --------------------------------------------------------------------------
# import
# --------------------------------------------------------------------------

def extract(zip_file):
    """Read an Overleaf zip into {path: bytes}, safely. Returns (files, notes)."""
    notes = []
    members = {}
    total = 0
    with zipfile.ZipFile(zip_file) as zf:
        bad = zf.testzip()
        if bad is not None:
            sys.exit("import: the zip is corrupt at %s" % bad)
        for info in zf.infolist():
            name = info.filename
            if name.endswith("/"):
                continue
            # A symlink in a zip is a mode in the external attributes. Nothing
            # in this package is one; refuse rather than follow it anywhere.
            if (info.external_attr >> 16) & 0o170000 == 0o120000:
                notes.append("refused a symlink: %s" % name)
                continue
            norm = os.path.normpath(name.replace("\\", "/"))
            if os.path.isabs(norm) or norm.startswith("..") or \
                    ".." in norm.split("/"):
                notes.append("refused a path that escapes the package: %s" % name)
                continue
            if info.file_size > MAX_MEMBER_BYTES:
                notes.append("refused %s: %d bytes, over the %d-byte cap"
                             % (name, info.file_size, MAX_MEMBER_BYTES))
                continue
            total += info.file_size
            if total > MAX_TOTAL_BYTES:
                sys.exit("import: the zip expands past %d bytes; refusing"
                         % MAX_TOTAL_BYTES)
            members[norm] = zf.read(info)

    # Some browsers and file managers repack a download inside one folder.
    tops = {p.split("/", 1)[0] for p in members if "/" in p}
    roots = {p for p in members if "/" not in p}
    if not roots and len(tops) == 1:
        top = tops.pop()
        members = {p[len(top) + 1:]: b for p, b in members.items()}
        notes.append("stripped the wrapping directory %r from every path" % top)
    return members, notes


def ignorable(path):
    base = os.path.basename(path)
    if path.startswith("__MACOSX/") or base.startswith("._"):
        return True
    return base in IGNORE_NAME or path.endswith(IGNORE_SUFFIX)


def cmd_import(args):
    dry = args.dry_run
    zip_file = os.path.abspath(os.path.expanduser(args.zip))
    outside_repo(zip_file, "the zip")
    if not os.path.exists(zip_file):
        sys.exit("no such file: %s" % zip_file)
    print("== reading %s" % zip_file)
    members, notes = extract(zip_file)
    for n in notes:
        print("  %s" % n)
    print("  %d files in the zip" % len(members))

    if not dry:
        porcelain = git("status", "--porcelain")
        if porcelain and not args.allow_dirty:
            print()
            print("REFUSED: the working tree has uncommitted changes.")
            print("The import writes into the manuscript, and `git diff` is how")
            print("you read what it did; a dirty tree mixes the two. Commit or")
            print("stash first, or pass --allow-dirty if you mean to mix them.")
            for line in porcelain.splitlines()[:20]:
                print("  %s" % line)
            return 2

    # ---- the manifest, and what it is for -------------------------------
    manifest = None
    if MANIFEST in members:
        try:
            manifest = json.loads(members[MANIFEST].decode("utf-8"))
        except (ValueError, UnicodeDecodeError) as e:
            print("  the manifest is present but unreadable (%s)" % e)
    if manifest is None:
        print()
        print("NO MANIFEST in the zip (%s)." % MANIFEST)
        print("Without it there is no record of what was exported, so a file")
        print("that differs from the repository cannot be told apart two ways:")
        print("your edit in Overleaf, or a change made in the repository after")
        print("the export. Applying the second reverts work silently.")
        if not args.no_manifest_ok:
            print("Pass --no-manifest-ok to proceed anyway, having read that.")
            return 2
        print("Proceeding on --no-manifest-ok: every difference is treated as")
        print("an Overleaf edit, and `git diff` is the only check on that.")
    else:
        print("  manifest: exported %s from commit %s%s"
              % (manifest.get("exported", "?"), (manifest.get("commit") or "?")[:12],
                 ", tree dirty" if manifest.get("commit_dirty") else ""))

    known = {z: r for z, r in package_files()}
    base = (manifest or {}).get("files", {})

    apply_set = {}          # repo path -> new text
    unchanged, skipped, conflicts, problems, reports = [], [], [], [], []

    # ---- classify every file in the zip ----------------------------------
    for zip_rel in sorted(members):
        raw = members[zip_rel]
        if zip_rel in SCAFFOLD:
            continue
        if ignorable(zip_rel):
            skipped.append((zip_rel, "build product or OS file"))
            continue
        if zip_rel in GENERATED:
            skipped.append((zip_rel, "generated from ORDER.tsv; regenerated below"))
            continue
        repo_rel = known.get(zip_rel)
        if repo_rel is None:
            reports.append(("new file", zip_rel,
                            "not part of the package; a new section needs rows "
                            "in ORDER.tsv, outline.tsv and ledger.tsv, which "
                            "this tool does not write"))
            continue

        abs_repo = os.path.join(common.REPO, repo_rel)
        current = read_bytes(abs_repo) if os.path.exists(abs_repo) else b""
        text, norm_notes = normalize(raw, current)
        if text is None:
            problems.append("%s: %s" % (zip_rel, "; ".join(norm_notes)))
            continue
        for n in norm_notes:
            reports.append(("normalized", zip_rel, n))

        text, err = rewrite(zip_rel, text, forward=False)
        if err:
            problems.append("%s: %s" % (zip_rel, err))
            continue

        theirs = sha256(text.encode("utf-8"))
        ours = sha256(current) if current else None

        if theirs == ours:
            unchanged.append(zip_rel)
            continue

        rec = base.get(zip_rel)
        if rec is None:
            apply_set[repo_rel] = text          # no baseline: treat as an edit
            continue
        base_repo = rec.get("repo_sha256")
        if theirs == base_repo:
            # Overleaf did not touch it; the repository moved instead.
            skipped.append((zip_rel, "unedited in Overleaf; the repository "
                                     "changed it since the export"))
            continue
        if ours != base_repo and not args.force:
            conflicts.append(zip_rel)
            continue
        apply_set[repo_rel] = text

    # ---- files that were exported and did not come back ------------------
    for zip_rel in sorted(base):
        if zip_rel in members or zip_rel in SCAFFOLD:
            continue
        reports.append(("missing", zip_rel,
                        "exported but not in the returned zip; deleted or "
                        "renamed in Overleaf. Nothing is deleted here"))

    # ---- structural analysis, before anything is written -----------------
    _, order = common.read_tsv(os.path.join(common.SECTIONS, "ORDER.tsv"))
    by_path = {r["path"]: r for r in order}
    retitles = []
    for repo_rel, text in sorted(apply_set.items()):
        row = by_path.get(repo_rel)
        if row is None:
            continue                     # book.tex, preamble.tex, refs.bib
        h = heading_of(text)
        if h is None:
            problems.append("%s: no longer opens with a heading command and a "
                            "\\label{sec:N}; check_structure.py requires both"
                            % zip_path_for(repo_rel))
            continue
        cmd, starred, num, title = h
        # D-415: the depth a file must keep is the depth it left with, not one
        # derived from its number. D-406 made ORDER.tsv's num a stable identity
        # that matches the filename and the ledger key, so a num with three
        # dotted parts can legitimately print as a section -- chapter 13 has
        # three. common.level(num) read that as a depth change and returned 2
        # with nothing written, which would block an import over files Overleaf
        # never touched.
        abs_ours = os.path.join(common.REPO, repo_rel)
        ours_h = (heading_of(read_bytes(abs_ours).decode("utf-8"))
                  if os.path.exists(abs_ours) else None)
        # D-463, and the same correction one branch over: the label a file must
        # keep is the label it left with, not ORDER.tsv's num. D-461 made every
        # heading label a name -- sec:anyway, ch:route -- while num stays the
        # numeric identity the ledger is keyed on, so comparing the two called
        # every file a renumber and returned 2 with nothing written, over an
        # edit that changed one word. check_structure.py exempts a named label
        # from the same comparison for the same reason. Against the repository's
        # own copy the check still catches what it was built for: a label
        # changed in Overleaf, which is a renumber or a rename either way and
        # needs a map and a sweep of every \ref pointing at it.
        theirs = ours_h[2] if ours_h else row["num"]
        if num != theirs:
            problems.append("%s: the label came back as %s and the repository's "
                            "is %s. Changing a label needs a map and a sweep of "
                            "every \\ref pointing at it"
                            % (zip_path_for(repo_rel), num, theirs))
            continue
        want = ours_h[0] if ours_h else cmd
        if cmd != want:
            problems.append("%s: heading is \\%s and the repository's is \\%s. "
                            "Changing the depth renumbers the book"
                            % (zip_path_for(repo_rel), cmd, want))
            continue
        if title != row["title"]:
            retitles.append((num, row["title"], title))

    # ---- report ----------------------------------------------------------
    print()
    print("== what came back")
    print("  %d to apply, %d unchanged, %d skipped, %d conflicts, %d problems"
          % (len(apply_set), len(unchanged), len(skipped), len(conflicts),
             len(problems)))
    for repo_rel in sorted(apply_set):
        print("  edit      %s" % repo_rel)
    for zip_rel, why in sorted(skipped):
        print("  skip      %s -- %s" % (zip_rel, why))
    for kind, zip_rel, why in sorted(reports):
        print("  %-9s %s -- %s" % (kind, zip_rel, why))
    if retitles:
        print()
        print("== retitled sections (%d)" % len(retitles))
        for num, old, new in retitles:
            print("  %s" % num)
            print("    was: %s" % old)
            print("    now: %s" % new)

    if conflicts:
        print()
        print("== CONFLICTS (%d): changed in Overleaf AND in the repository"
              % len(conflicts))
        for zip_rel in conflicts:
            print("  %s" % zip_rel)
            print("    repo: %s" % known[zip_rel])
        print("Both versions moved since the export, so one of them would be")
        print("lost. Reconcile by hand -- the Overleaf text is in the zip and")
        print("the repository's is on disk -- or pass --force to take Overleaf's")
        print("and read `git diff` for what it overwrote.")

    if problems:
        print()
        print("== STRUCTURAL PROBLEMS (%d)" % len(problems))
        for p in problems:
            print("  %s" % p)
        print("Nothing was written. These are changes the repository has to make")
        print("itself: they touch ORDER.tsv, outline.tsv, ledger.tsv and the")
        print("cross-references, none of which are in the Overleaf package.")
        return 2

    if conflicts:
        print()
        print("Nothing was written.")
        return 2

    if not apply_set and not retitles:
        print()
        print("Nothing to apply: the zip matches the repository.")
        return 0

    if dry:
        print()
        print("--dry-run: nothing written. Re-run without it to apply.")
        return 0

    # ---- apply -----------------------------------------------------------
    print()
    print("== applying")
    for repo_rel, text in sorted(apply_set.items()):
        with open(os.path.join(common.REPO, repo_rel), "w",
                  encoding="utf-8", newline="") as f:
            f.write(text)
        print("  wrote %s" % repo_rel)

    if retitles and not args.no_sync_titles:
        print()
        print("== syncing the title copies (the .tex heading wins, D-011)")
        targets = [(os.path.join(common.SECTIONS, "ORDER.tsv"), 1, 2, "ORDER.tsv"),
                   (common.OUTLINE_TSV, 0, 1, "outline.tsv"),
                   (common.LEDGER_TSV, 0, 1, "ledger.tsv")]
        for num, _old, new in retitles:
            for path, key_idx, val_idx, label in targets:
                if not os.path.exists(path):
                    continue
                if set_tsv_cell(path, key_idx, num, val_idx, new):
                    print("  %-11s %s -> %s" % (label, num, new))
    elif retitles:
        print()
        print("  --no-sync-titles: the three title copies are left stale.")
        print("  check_structure.py will fail on ORDER.tsv until they are fixed.")

    # ---- repair ----------------------------------------------------------
    print()
    print("== regenerating what the edit invalidated")
    run_tool("finishing/tools/refresh_order_shas.py")
    run_tool("finishing/tools/gen_book.py")
    run_tool("finishing/tools/headings.py", "--write-toc")

    print()
    print("== invariants")
    rc = run_tool("bash", "finishing/tools/check_all.sh")

    print()
    print("Applied %d file(s)%s." % (len(apply_set),
                                     " and %d retitle(s)" % len(retitles)
                                     if retitles else ""))
    if rc:
        print("check_all.sh FAILED. Read it above; the tree is mid-repair.")
        print("`git diff` shows everything this import did, and `git checkout")
        print("--` on a path undoes it.")
    else:
        print("check_all.sh passed. Next:")
        print("  git diff                              read what changed")
        print("  finishing/tools/build_tex.sh          confirm it still builds")
    return 1 if rc else 0


# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description="Round-trip the manuscript through Overleaf.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Packages live outside the repository; ~/book-scratch/overleaf/ is the default,
and a path under the repository root is refused in both directions.

  overleaf.py export                    write the package
  overleaf.py import ZIP --dry-run      report, write nothing  DO THIS FIRST
  overleaf.py import ZIP                apply, repair, check

Set the compiler to LuaLaTeX in Overleaf (gear icon -> Compiler); the book does
not build under pdfLaTeX. The main document is book.tex. Retitling a section is
safe. Renumbering one, adding one, or deleting one is not, and stops the import
with nothing written.
""")
    sub = ap.add_subparsers(dest="cmd", required=True)

    e = sub.add_parser("export", help="write an Overleaf package")
    e.add_argument("-o", "--out",
                   help="zip to write, outside the repository "
                        "(default: ~/book-scratch/overleaf/"
                        "antifascist-intelligence_<date>.zip)")
    e.add_argument("--no-check", action="store_true",
                   help="skip check_all.sh before packaging")
    e.set_defaults(func=cmd_export)

    i = sub.add_parser("import", help="apply a zip downloaded from Overleaf")
    i.add_argument("zip", help="the zip from Overleaf (Menu -> Download -> "
                               "Source), from anywhere outside the repository")
    i.add_argument("--dry-run", action="store_true",
                   help="report what would happen and write nothing")
    i.add_argument("--allow-dirty", action="store_true",
                   help="import onto a tree with uncommitted changes")
    i.add_argument("--no-manifest-ok", action="store_true",
                   help="proceed with a zip that has no manifest, losing "
                        "the ability to tell an Overleaf edit from a repo one")
    i.add_argument("--force", action="store_true",
                   help="on a conflict, take Overleaf's copy")
    i.add_argument("--no-sync-titles", action="store_true",
                   help="do not update the title copies in ORDER.tsv, "
                        "outline.tsv and ledger.tsv after a retitle")
    i.set_defaults(func=cmd_import)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
