#!/usr/bin/env python3
"""The human-check tracker for the bibliography, and the draft-status macros.

Every entry in finishing/refs.bib gets one row in finishing/refs-ledger.tsv.
AGENT CHECKS ARE LABELLED AS SUCH IN THE NOTES (D-385). A note or addendum
recording work this repository's agents did says "agent-verified" or
"agent-checked", never a bare "verified". Notes print in the References, and the
footer on every page prints N/M "bibliographic entries human-checked" from the
`checked` column below -- so an unlabelled "Verified 2026-09-18" in the back of
the book read as the check the footer counts, while the footer said 0. 66 of 275
entries carried that wording. Write the label into any new note; nothing enforces
it, because a check that read the notes would be guessing at which sense of
"checked" a sentence meant, and three in the file are about a source or a system
rather than about us.

The row says whether a human has checked that entry against the source it
names -- that the work exists, that the author, year and venue are right, and
that the book's use of it is not a misreading.

    checked   yes | no        the only two values; --check rejects anything else
    date      YYYY-MM-DD      when it was checked
    by        initials        who checked it
    notes     free text       what was wrong, what was fixed, what to watch

Mark one from the shell, or edit the TSV by hand -- the file is the interface:

    finishing/tools/refs_ledger.py --mark kirkpatrick1983annealing --by jgs
    finishing/tools/refs_ledger.py --unmark kirkpatrick1983annealing
    finishing/tools/refs_ledger.py --toggle kirkpatrick1983annealing --by jgs

--toggle flips each key it is given and prints where each one landed; --by is
recorded for any key it turns checked. All three take several keys at once.
After a hand edit of the TSV, run the script with no arguments.

A plain run syncs the ledger to refs.bib and regenerates
manuscript/draft-status.tex: the two counts the preamble's footer prints, and
one \refcheckedkey{KEY} line per checked entry, which is what the draft
highlight reads -- every in-text citation of an entry not listed there is set
on an orange highlight (preamble.tex, D-641). Marking an entry checked takes
the highlight off at the next build.
--check is the invariant check_all.sh runs: it fails if the ledger has drifted
from the bibliography or if the generated macros are stale, so the count
printed in the footer of every page of the PDF cannot say something the
ledger does not.

The build timestamp in that footer is NOT generated here. It is computed by
TeX at compile time, so that this file stays stable between builds and --check
means something.
"""
import argparse
import datetime
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common  # noqa: E402

BIB = os.path.join(common.REPO, "finishing", "refs.bib")
LEDGER = os.path.join(common.REPO, "finishing", "refs-ledger.tsv")
STATUS_TEX = os.path.join(common.REPO, "manuscript", "draft-status.tex")

HEADER = ["key", "checked", "date", "by", "notes"]
ENTRY_RE = re.compile(r"^@(\w+)\s*\{\s*([^,\s]+)\s*,", re.MULTILINE)

STATUS_HEAD = """%% draft-status.tex -- GENERATED by finishing/tools/refs_ledger.py from
%% finishing/refs-ledger.tsv. Do not edit by hand; edits here are overwritten.
%%
%% The footer on every page prints these two numbers, and the draft highlight
%% leaves unmarked every citation of a key listed below by \\refcheckedkey. They
%% are regenerated from the ledger and checked by check_all.sh, so the page cannot
%% claim a count or a check the ledger does not carry.
"""


def bib_keys():
    """Every entry key in refs.bib, in file order. @string/@comment are not entries."""
    text = open(BIB, encoding="utf-8").read()
    keys, seen, dupes = [], set(), []
    for kind, key in ENTRY_RE.findall(text):
        if kind.lower() in ("string", "comment", "preamble"):
            continue
        if key in seen:
            dupes.append(key)
            continue
        seen.add(key)
        keys.append(key)
    return keys, dupes


def read_ledger():
    if not os.path.exists(LEDGER):
        return []
    _, rows = common.read_tsv(LEDGER)
    return rows


def synced(keys, rows):
    """The ledger as it should be: one row per bib key, bib order, rows kept."""
    have = {r["key"]: r for r in rows}
    out = [have.get(k, {"key": k, "checked": "no", "date": "", "by": "", "notes": ""})
           for k in keys]
    orphans = [r for r in rows if r["key"] not in set(keys)]
    return out, orphans


def counts(rows):
    n = sum(1 for r in rows if r.get("checked", "").strip().lower() == "yes")
    return n, len(rows)


def status_tex(rows):
    n, total = counts(rows)
    checked = "".join("\\refcheckedkey{%s}\n" % r["key"] for r in rows
                      if r.get("checked", "").strip().lower() == "yes")
    return STATUS_HEAD + ("\\newcommand{\\refschecked}{%d}\n"
                          "\\newcommand{\\refstotal}{%d}\n" % (n, total)) + checked


def bad_values(rows):
    return [r["key"] for r in rows
            if r.get("checked", "").strip().lower() not in ("yes", "no")]


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="verify the ledger and the generated macros; write nothing")
    ap.add_argument("--mark", metavar="KEY", nargs="+", help="mark entries checked")
    ap.add_argument("--unmark", metavar="KEY", nargs="+", help="mark entries unchecked")
    ap.add_argument("--toggle", metavar="KEY", nargs="+",
                    help="flip each entry between checked and unchecked")
    ap.add_argument("--by", default="", help="initials to record with --mark or --toggle")
    ap.add_argument("--date", default=datetime.date.today().isoformat(),
                    help="date to record with --mark or --toggle (default: today)")
    ap.add_argument("--note", default=None,
                    help="note to record with --mark, --unmark or --toggle")
    args = ap.parse_args()

    keys, dupes = bib_keys()
    rows, orphans = synced(keys, read_ledger())
    by_key = {r["key"]: r for r in rows}

    if dupes:
        print("refs.bib has duplicate keys: " + " ".join(sorted(set(dupes))))
        return 1

    if args.check:
        bad = bad_values(rows)
        problems = []
        if not os.path.exists(LEDGER):
            problems.append("refs-ledger.tsv does not exist; run refs_ledger.py")
        if orphans:
            problems.append("ledger rows for keys no longer in refs.bib: "
                            + " ".join(r["key"] for r in orphans))
        missing = [k for k in keys if k not in {r["key"] for r in read_ledger()}]
        if missing:
            problems.append("refs.bib keys with no ledger row: " + " ".join(missing))
        if bad:
            problems.append("checked must be yes or no: " + " ".join(bad))
        want = status_tex(rows)
        got = open(STATUS_TEX, encoding="utf-8").read() if os.path.exists(STATUS_TEX) else None
        if got != want:
            problems.append("draft-status.tex is stale; re-run refs_ledger.py")
        if problems:
            for p in problems:
                print("refs ledger STALE: " + p)
            return 1
        n, total = counts(rows)
        print("refs ledger OK: %d/%d checked, %d entries, macros current"
              % (n, total, total))
        return 0

    marked, unmarked = [], []
    toggles = list(args.toggle or [])
    for key in toggles:
        if key not in by_key:
            print("no such bib key: %s" % key)
            return 1
    for key in toggles:
        if by_key[key].get("checked", "").strip().lower() == "yes":
            args.unmark = (args.unmark or []) + [key]
        else:
            args.mark = (args.mark or []) + [key]
    for key in (args.mark or []):
        if key not in by_key:
            print("no such bib key: %s" % key)
            return 1
        by_key[key].update(checked="yes", date=args.date, by=args.by)
        if args.note is not None:
            by_key[key]["notes"] = args.note
        marked.append(key)
    for key in (args.unmark or []):
        if key not in by_key:
            print("no such bib key: %s" % key)
            return 1
        by_key[key].update(checked="no", date="", by="")
        if args.note is not None:
            by_key[key]["notes"] = args.note
        unmarked.append(key)

    for r in orphans:
        print("dropped ledger row, key gone from refs.bib: %s (was checked=%s)"
              % (r["key"], r.get("checked", "")))
    added = [k for k in keys if k not in {r["key"] for r in read_ledger()}]
    for k in added:
        print("new bib key, added unchecked: %s" % k)

    common.write_tsv(LEDGER, HEADER, rows)
    with open(STATUS_TEX, "w", encoding="utf-8") as f:
        f.write(status_tex(rows))

    n, total = counts(rows)
    if marked:
        print("marked checked: " + " ".join(marked))
    if unmarked:
        print("marked unchecked: " + " ".join(unmarked))
    print("wrote %s and %s: %d/%d checked"
          % (os.path.relpath(LEDGER, common.REPO),
             os.path.relpath(STATUS_TEX, common.REPO), n, total))
    return 0


if __name__ == "__main__":
    sys.exit(main())
